import { CharacterClass, CharacterClassId } from '../types';

/** 每职业每级成长（数值平衡 2026-09：原全局 +15HP/+2攻，法力与防御零成长，现按职业分档） */
export interface ClassGrowth {
  hp: number;      // 每级最大生命
  attack: number;  // 每级攻击
  defense: number; // 每级防御
  mana: number;    // 每级最大法力
}

export const CLASS_GROWTH: Record<CharacterClassId, ClassGrowth> = {
  warrior: { hp: 18, attack: 2, defense: 1, mana: 5 },
  ranger: { hp: 8, attack: 2, defense: 1, mana: 8 },
  mage: { hp: 6, attack: 1, defense: 1, mana: 14 },
  rogue: { hp: 7, attack: 2, defense: 1, mana: 8 },
  summoner: { hp: 8, attack: 1, defense: 1, mana: 12 },
  druid: { hp: 12, attack: 1, defense: 1, mana: 10 },
};

export const CLASS_DEFINITIONS: Record<CharacterClassId, CharacterClass> = {
  warrior: {
    id: 'warrior',
    name: '狂战士 (Berserker)',
    title: '近战巨力 · 嗜血狂暴',
    description: '擅长正面冲锋与剑盾格挡，生命值低下时激活狂暴怒火，获得爆发攻击力与吸血。',
    icon: '⚔️',
    themeColor: '#ef4444',
    baseStats: {
      hp: 160,
      maxHp: 160,
      mana: 80,
      maxMana: 80,
      attack: 18,
      defense: 8,
      critChance: 0.12,
      speed: 5.0,
      lifeSteal: 0.08,
    },
    passiveName: '血之狂怒 (Blood Rage)',
    passiveDesc: '生命值低于 50% 时，攻击力提升 35%，移速提升 15%，且攻击附带额外 10% 吸血。',
    startingGearSummary: '炽钢重剑 + 破阵精钢重盾 + 禁卫玄铁重铠 + 破阵战靴',
    primaryAttackDesc: '【重剑三连斩】一段横扫 -> 二段挑劈 -> 三段跳跃震地重砸AOE冲击波',
    secondaryAttackDesc: '【破阵坚毅壁垒】架盾格挡减伤80%且反弹飞弹，松开释放盾猛震荡波',
  },
  ranger: {
    id: 'ranger',
    name: '神射手 (Marksman)',
    title: '鹰眼贯穿 · 疾风漫游',
    description: '远程游击射术宗师，弓箭充能更快，箭矢自带额外穿透，远距离狙击暴击极高。',
    icon: '🏹',
    themeColor: '#10b981',
    baseStats: {
      hp: 100,
      maxHp: 100,
      mana: 90,
      maxMana: 90,
      attack: 14,
      defense: 4,
      critChance: 0.28,
      speed: 6.0,
      lifeSteal: 0.0,
    },
    passiveName: '鹰眼神射 (Eagle Eye)',
    passiveDesc: '弓箭蓄力速度加快 40%，箭矢贯穿 1 个额外敌人；对 3.5 格外的敌人暴击伤害提升 60%。',
    startingGearSummary: '疾风追猎长弓 + 穿心猎手轻匕 + 巡林客风行皮甲 + 疾行长靴',
    primaryAttackDesc: '【连珠迅捷平射】超高攻速连发疾风箭矢，超快走A风筝敌群',
    secondaryAttackDesc: '【破空贯穿狙击】蓄力射出贯穿重箭，100%穿透敌群并造成强力击退',
  },
  mage: {
    id: 'mage',
    name: '奥术学者 (Arcanist)',
    title: '奥术共鸣 · 元素爆发',
    description: '通晓古代符文与炼金法阵，全部技能冷却大幅缩减，喝药水时爆发出奥术震荡波。',
    icon: '🔮',
    themeColor: '#a855f7',
    baseStats: {
      hp: 90,
      maxHp: 90,
      mana: 160,
      maxMana: 160,
      attack: 13,
      defense: 3,
      critChance: 0.18,
      speed: 5.2,
      lifeSteal: 0.03,
    },
    passiveName: '奥术共鸣 (Arcane Surge)',
    passiveDesc: '所有技能冷却缩短 30%，使用药水额外恢复 35 点生命并释放击退周围怪物的奥术冲击波。',
    startingGearSummary: '星界水晶法杖 + 远古预言秘典 + 星辉织锦法袍 + 秘术聚焦戒',
    primaryAttackDesc: '【奥术魔法弹】单发高速奥术飞弹，消耗微量法力，附带溅射粒子',
    secondaryAttackDesc: '【蓄力元素爆破】扇形齐射三枚炽焰能量球，在落点引发范围元素大爆炸',
  },
  rogue: {
    id: 'rogue',
    name: '暗影刺客 (Shadowblade)',
    title: '迅捷身法 · 致命背刺',
    description: '行走于虚空的暗影行者，身法极快，翻滚释放致盲烟幕，从侧背突袭造成巨额暴击。',
    icon: '🗡️',
    themeColor: '#06b6d4',
    baseStats: {
      hp: 85,
      maxHp: 85,
      mana: 100,
      maxMana: 100,
      attack: 16,
      defense: 3,
      critChance: 0.28, // 数值平衡(2026-09)：0.35→0.28（修复暴击双算后 1 级曾近 100% 暴击）
      speed: 6.5,
      lifeSteal: 0.04,
    },
    passiveName: '绝影背刺 (Shadow Ambush)',
    passiveDesc: '翻滚冲刺冷却缩短 40% 并在原地留下致盲烟幕；在目标侧面或背后攻击造成 1.85 倍背刺伤害！',
    startingGearSummary: '影杀利刃 (主手) + 剧毒淬血刺 (副手) + 暗夜潜行衣 + 绝影软靴',
    primaryAttackDesc: '【极速双刃刺】超频双匕切割，侧背突袭触发 1.85x 背刺暴击与流血',
    secondaryAttackDesc: '【暗影扇形飞刀】向前方散射 5 柄淬毒暗影飞刀，附带持续剧毒流血减速',
  },
  summoner: {
    id: 'summoner',
    name: '通灵召唤师 (Summoner)',
    title: '幽魂驱策 · 亡者战团',
    description: '能够沟通彼岸亡灵与魔狼仆从，指挥召唤大军冲锋撕咬，自身提供群体狂暴与灵魂收割。',
    icon: '💀',
    themeColor: '#6366f1',
    baseStats: {
      hp: 95,
      maxHp: 95,
      mana: 180,
      maxMana: 180,
      attack: 12,
      defense: 3,
      critChance: 0.15,
      speed: 5.3,
      lifeSteal: 0.05,
    },
    passiveName: '亡者军势 (Legion Command)',
    passiveDesc: '召唤物伤害与攻击速度提升 30%，自身受到的 25% 伤害由存活随从分摊。',
    startingGearSummary: '噬魂灵木法杖 + 亡者低语头骨 + 唤灵玄黑法袍 + 幽魂之戒',
    primaryAttackDesc: '【灵魂收割飞弹】发射穿透灵魂矢，击中敌人时微量恢复自身生命与法力',
    secondaryAttackDesc: '【唤灵法阵/狂暴嗜血】召唤幽暗魔狼群；若战场已有仆从，则全员狂暴提速+50%！',
  },
  druid: {
    id: 'druid',
    name: '荒野德鲁伊 (Druid)',
    title: '自然律动 · 巨熊狂暴',
    description: '调和大地自然与野性生机，普攻附带荆棘毒刺缠绕，右键化身狂暴巨熊震碎大地击飞群怪。',
    icon: '🐾',
    themeColor: '#15803d',
    baseStats: {
      hp: 130,
      maxHp: 130,
      mana: 140,
      maxMana: 140,
      attack: 15,
      defense: 6,
      critChance: 0.16,
      speed: 5.4,
      lifeSteal: 0.06,
    },
    passiveName: '大地生机 (Gift of the Wild)',
    passiveDesc: '受到攻击时触发荆棘反弹 40% 伤害，脱战或使用技能时每 2 秒恢复 3% 最大生命与法力。',
    startingGearSummary: '世界树萌芽权杖 + 翡翠橡木神符 + 荒野林地轻袍 + 自然守护戒',
    primaryAttackDesc: '【自然荆棘法弹】释放缠绕藤蔓法球，击中产生自然花粉爆炸并造成剧毒',
    secondaryAttackDesc: '【野性之怒·巨熊重踏】化身远古巨熊拍击大地，造成 360° 崩裂波并获得树皮护盾',
  },
};
