import { EquippedGear } from '../types';

export class MagicClassGearFactory {
  public static generateMageGear(timeId: number): EquippedGear {
    return {
      weapon: {
        id: `wp_mag_${timeId}`,
        name: '星界水晶法杖 (Astral Staff)',
        rarity: 'magic',
        slot: 'weapon',
        subType: 'staff',
        level: 1,
        icon: '🪄',
        attackBonus: 15,
        critChanceBonus: 0.12,
        attackSpeedRating: 'A',
        weaponRange: 11.0,
        weaponSweepArc: 0,
        knockbackForce: 3.0,
        refineLevel: 0,
        recommendedClass: 'mage',
        glowColor: '#a855f7',
        glowIntensity: 0.9,
        vfxType: '引导式奥术飞弹',
        appearanceDesc: '紫芒水晶杖首凝结自动诱导星界魔能，飞弹具备主动寻踪轨迹',
        weaponPerk: '奥术共鸣：普攻连续发射奥术飞弹，右键释放高爆元素烈焰',
        description: '蕴含星界奥术能量的长杖，普攻发射奥术魔法飞弹，右键释放蓄力元素爆破',
        affixes: ['法术飞弹攻击 +15', '暴击率 +12%', '法术穿透 +1'],
        value: 45,
      },
      offhand: {
        id: `oh_mag_${timeId}`,
        name: '远古预言秘典 (Ancient Tome)',
        rarity: 'magic',
        slot: 'offhand',
        subType: 'totem',
        level: 1,
        icon: '📖',
        hpBonus: 20,
        defenseBonus: 2,
        description: '记载古代秘法印记的禁忌法典，大幅缩减全技能冷却并提升法力上限',
        affixes: ['技能冷却 -20%', '最大法力 +40', '法术吸血 +3%'],
        value: 50,
      },
      armor: {
        id: `ar_mag_${timeId}`,
        name: '星辉织锦法袍',
        rarity: 'common',
        slot: 'armor',
        level: 1,
        icon: '👘',
        defenseBonus: 3,
        hpBonus: 20,
        description: '流淌着微弱魔力光晕的学者法袍，提供魔力共鸣保护',
        affixes: ['最大法力 +35', '魔法护盾 +10'],
        value: 25,
      },
      helmet: null,
      boots: null,
      ring: {
        id: `rg_mag_${timeId}`,
        name: '秘术聚焦之戒',
        rarity: 'magic',
        slot: 'ring',
        level: 1,
        icon: '💍',
        critChanceBonus: 0.08,
        description: '刻有汇聚法力符文的秘银魔戒，大幅降低全法术法力消耗',
        affixes: ['法力消耗 -15%', '暴击率 +8%'],
        value: 40,
      },
    };
  }

  public static generateSummonerGear(timeId: number): EquippedGear {
    return {
      weapon: {
        id: `wp_sum_${timeId}`,
        name: '噬魂灵木法杖 (Spirit Wand)',
        rarity: 'magic',
        slot: 'weapon',
        subType: 'wand',
        level: 1,
        icon: '🔮',
        attackBonus: 14,
        critChanceBonus: 0.14,
        attackSpeedRating: 'A',
        weaponRange: 10.5,
        weaponSweepArc: 0,
        knockbackForce: 2.8,
        refineLevel: 0,
        recommendedClass: 'summoner',
        glowColor: '#6366f1',
        glowIntensity: 0.92,
        vfxType: '灵魂收割辉芒',
        appearanceDesc: '盘绕着幽白灵火的古木法杖，飞弹具有穿透并掠夺微量生命之力',
        weaponPerk: '灵魂收割：普攻穿透飞弹汲取生命，右键狂暴号令所有随从',
        description: '沟通冥灵的古老手杖，能够汲取敌方灵魂，右键召唤或狂暴狼群',
        affixes: ['灵魂穿透 +2', '随从伤害 +25%', '击中回蓝 +3'],
        value: 50,
      },
      offhand: {
        id: `oh_sum_${timeId}`,
        name: '亡者低语头骨 (Skull Totem)',
        rarity: 'magic',
        slot: 'offhand',
        subType: 'totem',
        level: 1,
        icon: '💀',
        hpBonus: 25,
        defenseBonus: 3,
        description: '幽暗眼眶中燃烧着冷焰的通灵图腾，强化随从生命与攻击',
        affixes: ['随从攻击 +30%', '随从生命 +40', '受创伤害由随从分摊 25%'],
        value: 55,
      },
      armor: {
        id: `ar_sum_${timeId}`,
        name: '唤灵玄黑法袍',
        rarity: 'common',
        slot: 'armor',
        level: 1,
        icon: '🥋',
        defenseBonus: 3,
        hpBonus: 25,
        description: '编织了冥界丝线的黑袍，能够抵御死灵侵蚀',
        affixes: ['最大法力 +45', '受创回血 +5'],
        value: 30,
      },
      helmet: null,
      boots: null,
      ring: {
        id: `rg_sum_${timeId}`,
        name: '幽魂誓约之戒',
        rarity: 'magic',
        slot: 'ring',
        level: 1,
        icon: '💍',
        hpBonus: 15,
        description: '与契约随从共享生命力的魂戒，使随从持续时间延长 50%',
        affixes: ['随从存续时间 +50%', '法术暴击 +6%'],
        value: 42,
      },
    };
  }

  public static generateDruidGear(timeId: number): EquippedGear {
    return {
      weapon: {
        id: `wp_dru_${timeId}`,
        name: '世界树萌芽权杖 (Verdant Staff)',
        rarity: 'magic',
        slot: 'weapon',
        subType: 'staff',
        level: 1,
        icon: '🌿',
        attackBonus: 16,
        critChanceBonus: 0.12,
        attackSpeedRating: 'B',
        weaponRange: 10.0,
        weaponSweepArc: 0,
        knockbackForce: 3.5,
        refineLevel: 0,
        recommendedClass: 'druid',
        glowColor: '#22c55e',
        glowIntensity: 0.88,
        vfxType: '自然生机蔓延',
        appearanceDesc: '杖首绽放长青绿芽与自然花粉，法弹附带剧毒荆棘缠绕',
        weaponPerk: '荒野之怒：自然法弹缠绕减速，右键巨熊形态崩山裂地',
        description: '承载世界树祝福的自然神权杖，掌控植物荆棘与化身巨熊撕裂大地',
        affixes: ['自然剧毒 +16', '荆棘反弹 +35%', '回春再生 +4/s'],
        value: 50,
      },
      offhand: {
        id: `oh_dru_${timeId}`,
        name: '翡翠橡木神符 (Oak Talisman)',
        rarity: 'magic',
        slot: 'offhand',
        subType: 'totem',
        level: 1,
        icon: '🪵',
        hpBonus: 35,
        defenseBonus: 4,
        description: '浸润世界树汁液的橡木神符，持续提供生命与法力再生',
        affixes: ['每2秒回血 4%', '荆棘反震 40%', '护甲 +4'],
        value: 48,
      },
      armor: {
        id: `ar_dru_${timeId}`,
        name: '荒野林地轻袍',
        rarity: 'common',
        slot: 'armor',
        level: 1,
        icon: '🥻',
        defenseBonus: 5,
        hpBonus: 30,
        description: '由常青树皮与藤蔓编织的坚韧轻袍，兼具护甲与敏捷',
        affixes: ['生命上限 +30', '移速 +0.3'],
        value: 28,
      },
      helmet: null,
      boots: null,
      ring: {
        id: `rg_dru_${timeId}`,
        name: '自然守护者指环',
        rarity: 'magic',
        slot: 'ring',
        level: 1,
        icon: '💍',
        defenseBonus: 2,
        description: '铭刻大地之母守护印记的翡翠戒，受到攻击时激发生机吸收护盾',
        affixes: ['生命偷取 +4%', '受创吸收护盾 +20'],
        value: 38,
      },
    };
  }
}
