import { EnemyType } from '../types';

export interface MonsterConfig {
  type: EnemyType;
  name: string;
  baseHp: number;
  baseDamage: number;
  baseSpeed: number;
  baseDefense: number;
  attackRange: number;
  attackCooldown: number;
  windupTime: number;
  size: number;
  color: string;
}

export const MONSTER_CONFIGS: Record<EnemyType, MonsterConfig> = {
  zombie: {
    type: 'zombie',
    name: '僵尸 (Zombie)',
    baseHp: 80,
    baseDamage: 12,
    baseSpeed: 2.8,
    baseDefense: 3,
    attackRange: 1.25,
    attackCooldown: 1.2,
    windupTime: 0.35,
    size: 1.0,
    color: '#16a34a',
  },
  skeleton: {
    type: 'skeleton',
    name: '骷髅弓箭手 (Skeleton)',
    baseHp: 65,
    baseDamage: 14,
    baseSpeed: 3.2,
    baseDefense: 2,
    attackRange: 7.0,
    attackCooldown: 2.0,
    windupTime: 0.45,
    size: 1.0,
    color: '#e2e8f0',
  },
  creeper: {
    type: 'creeper',
    name: '苦力怕 (Creeper)',
    baseHp: 55,
    baseDamage: 60,
    baseSpeed: 3.6,
    baseDefense: 1,
    attackRange: 2.0,
    attackCooldown: 2.0,
    windupTime: 1.3,
    size: 1.0,
    color: '#22c55e',
  },
  spider: {
    type: 'spider',
    name: '洞穴蜘蛛 (Spider)',
    baseHp: 60,
    baseDamage: 10,
    baseSpeed: 4.4,
    baseDefense: 2,
    attackRange: 1.5,
    attackCooldown: 0.9,
    windupTime: 0.25,
    size: 1.1,
    color: '#1c1917',
  },
  enderman: {
    type: 'enderman',
    name: '末影人 (Enderman)',
    baseHp: 130,
    baseDamage: 22,
    baseSpeed: 3.5,
    baseDefense: 5,
    attackRange: 1.4,
    attackCooldown: 1.4,
    windupTime: 0.3,
    size: 1.35,
    color: '#0f0e17',
  },
  piglin_brute: {
    type: 'piglin_brute',
    name: '猪灵蛮兵 (Piglin Brute)',
    baseHp: 150,
    baseDamage: 24,
    baseSpeed: 3.4,
    baseDefense: 7,
    attackRange: 1.5,
    attackCooldown: 1.6,
    windupTime: 0.5,
    size: 1.25,
    color: '#f59e0b',
  },
  blaze: {
    type: 'blaze',
    name: '烈焰人 (Blaze)',
    baseHp: 90,
    baseDamage: 16,
    baseSpeed: 2.6,
    baseDefense: 4,
    attackRange: 7.5,
    attackCooldown: 2.2,
    windupTime: 0.5,
    size: 1.1,
    color: '#f97316',
  },
  necromancer: {
    type: 'necromancer',
    name: '死灵法师 (Necromancer)',
    baseHp: 110,
    baseDamage: 15,
    baseSpeed: 2.5,
    baseDefense: 4,
    attackRange: 8.0,
    attackCooldown: 2.8,
    windupTime: 0.6,
    size: 1.15,
    color: '#7c3aed',
  },
  slime: {
    type: 'slime',
    name: '史莱姆 (Slime)',
    baseHp: 75,
    baseDamage: 11,
    baseSpeed: 3.0,
    baseDefense: 2,
    attackRange: 1.3,
    attackCooldown: 1.1,
    windupTime: 0.3,
    size: 1.1,
    color: '#4ade80',
  },
  witch: {
    type: 'witch',
    name: '女巫 (Witch)',
    baseHp: 85,
    baseDamage: 18,
    baseSpeed: 2.7,
    baseDefense: 3,
    attackRange: 6.5,
    attackCooldown: 2.4,
    windupTime: 0.55,
    size: 1.05,
    color: '#9333ea',
  },
  drowned: {
    type: 'drowned',
    name: '溺尸 (Drowned)',
    baseHp: 95,
    baseDamage: 16,
    baseSpeed: 3.1,
    baseDefense: 4,
    attackRange: 4.5,
    attackCooldown: 1.8,
    windupTime: 0.45,
    size: 1.05,
    color: '#06b6d4',
  },
  armored_zombie: {
    type: 'armored_zombie',
    name: '重装战斗僵尸 (Armored Zombie)',
    baseHp: 160,
    baseDamage: 18,
    baseSpeed: 2.7,
    baseDefense: 10,
    attackRange: 1.45,
    attackCooldown: 1.4,
    windupTime: 0.4,
    size: 1.15,
    color: '#475569',
  },
  baby_zombie: {
    type: 'baby_zombie',
    name: '狂暴幼体僵尸 (Baby Zombie)',
    baseHp: 45,
    baseDamage: 10,
    baseSpeed: 5.6,
    baseDefense: 1,
    attackRange: 1.2,
    attackCooldown: 0.65,
    windupTime: 0.15,
    size: 0.6,
    color: '#22c55e',
  },
  chimera: {
    type: 'chimera',
    name: '奇美拉 (Chimera)',
    baseHp: 950,
    baseDamage: 32,
    baseSpeed: 3.4,
    baseDefense: 12,
    attackRange: 2.1,
    attackCooldown: 1.6,
    windupTime: 0.7,
    size: 2.6,
    color: '#d97706',
  },

  goblin: {
    type: 'goblin',
    name: '潜行盗宝哥布林 (Goblin Scout)',
    baseHp: 70,
    baseDamage: 15,
    baseSpeed: 4.8,
    baseDefense: 3,
    attackRange: 5.5,
    attackCooldown: 1.2,
    windupTime: 0.25,
    size: 0.8,
    color: '#eab308',
  },
  wither_boss: {
    type: 'wither_boss',
    name: '凋灵领主 (Wither Lord)',
    baseHp: 800,
    baseDamage: 32,
    baseSpeed: 2.6,
    baseDefense: 14,
    attackRange: 9.0,
    attackCooldown: 1.5,
    windupTime: 0.4,
    size: 1.85,
    color: '#1e1b4b',
  },
};
