import { WeaponSubType, CharacterClassId } from '../types';

export interface WeaponBaseStat {
  subType: string;
  name: string;
  emoji: string;
  speedRating: 'S' | 'A' | 'B' | 'C';
  baseCooldown: number; // Attack cooldown in seconds
  baseRange: number; // Range in units
  baseArc: number; // Swing arc in radians (0 for straight)
  baseKnockback: number;
  baseDmgMult: number;
  baseCritChance: number;
  recommendedClass: CharacterClassId;
  defaultVfxType: string;
  defaultGlowColor: string;
  glowIntensity: number;
  combatArchetype: 'cleave' | 'slam' | 'rapid_flurry' | 'snipe' | 'pierce' | 'homing_elemental' | 'elemental_rapid';
  perkName: string;
  perkDescription: string;
  styleDescription: string;
}

/** 双手武器集合：装备时占用双手槽位（副手自动卸下/禁止装备） */
export const TWO_HANDED_WEAPONS: ReadonlySet<string> = new Set([
  'greatsword', 'hammer', 'bow', 'crossbow',
]);

export function isTwoHandedWeapon(subType: string | undefined): boolean {
  return !!subType && TWO_HANDED_WEAPONS.has(subType);
}

export const WEAPON_BASE_CONFIGS: Record<string, WeaponBaseStat> = {
  sword: {
    subType: 'sword',
    name: '重剑 / 长剑 (Broadsword)',
    emoji: '⚔️',
    speedRating: 'B',
    baseCooldown: 0.28,
    baseRange: 2.3,
    baseArc: Math.PI * 0.75, // 135 deg
    baseKnockback: 4.5,
    baseDmgMult: 1.0,
    baseCritChance: 0.08,
    recommendedClass: 'warrior',
    defaultVfxType: 'slash_arc',
    defaultGlowColor: '#38bdf8',
    glowIntensity: 0.8,
    combatArchetype: 'cleave',
    perkName: '利刃横扫 (Cleaving Sweep)',
    perkDescription: '扇形范围内所有敌方单位受到全额挥砍伤害与击退',
    styleDescription: '均衡型近战武器，攻守兼备，狂战士装备时获得额外挥砍弧度与连招韧性。',
  },
  axe: {
    subType: 'axe',
    name: '战斧 / 重斧 (Battleaxe)',
    emoji: '🪓',
    speedRating: 'C',
    baseCooldown: 0.42,
    baseRange: 2.1,
    baseArc: Math.PI * 0.55, // 100 deg
    baseKnockback: 7.2,
    baseDmgMult: 1.45,
    baseCritChance: 0.12,
    recommendedClass: 'warrior',
    defaultVfxType: 'heavy_cleave',
    defaultGlowColor: '#f97316',
    glowIntensity: 1.1,
    combatArchetype: 'slam',
    perkName: '碎骨重击 (Bone Crusher)',
    perkDescription: '势沉力猛，对破甲目标造成巨额单发伤害并强力击退',
    styleDescription: '重型双手武器，挥舞较慢但单发致命，狂战士专精可转化为崩山裂地重击。',
  },
  greatsword: {
    subType: 'greatsword',
    name: '双手大剑 (Two-Handed Greatsword)',
    emoji: '🗡️',
    speedRating: 'C',
    baseCooldown: 0.46,
    baseRange: 2.8,
    baseArc: Math.PI * 0.95, // 170 deg massive sweep
    baseKnockback: 9.0,
    baseDmgMult: 1.65,
    baseCritChance: 0.14,
    recommendedClass: 'warrior',
    defaultVfxType: 'heavy_cleave',
    defaultGlowColor: '#fbbf24',
    glowIntensity: 1.2,
    combatArchetype: 'slam',
    perkName: '崩岳断罪 (Titan Cleave & Plunge)',
    perkDescription: '双手巨刃破空斩击，蓄力时可跃空而起重力插地引发大地崩裂冲击波',
    styleDescription: '双手持握的狂霸重刃，极具质量与转动惯量，兼具大范围清场与跃空斩击震荡。',
  },
  dagger: {
    subType: 'dagger',
    name: '匕首 / 短刃 (Shadow Dagger)',
    emoji: '🗡️',
    speedRating: 'S',
    baseCooldown: 0.14,
    baseRange: 1.6,
    baseArc: Math.PI * 0.4, // 72 deg
    baseKnockback: 1.8,
    baseDmgMult: 0.68,
    baseCritChance: 0.24,
    recommendedClass: 'rogue',
    defaultVfxType: 'thrust_sparks',
    defaultGlowColor: '#a855f7',
    glowIntensity: 0.9,
    combatArchetype: 'rapid_flurry',
    perkName: '致命背刺 (Shadow Assassinate)',
    perkDescription: '从目标后背攻击必定触发双倍暴击与剧毒流血',
    styleDescription: '极速敏捷型武器，攻速极致，游侠与刺客装备时触发超频连刺。',
  },
  bow: {
    subType: 'bow',
    name: '战弓 / 长弓 (War Bow)',
    emoji: '🏹',
    speedRating: 'B',
    baseCooldown: 0.24,
    baseRange: 14.0,
    baseArc: 0,
    baseKnockback: 3.5,
    baseDmgMult: 1.15,
    baseCritChance: 0.15,
    recommendedClass: 'ranger',
    defaultVfxType: 'arrow_trail',
    defaultGlowColor: '#10b981',
    glowIntensity: 0.85,
    combatArchetype: 'snipe',
    perkName: '百步穿杨 (Eagle Eye)',
    perkDescription: '射程极远，飞行距离越远命中时附带额外破甲伤害',
    styleDescription: '精准远程武器，神射手使用时箭矢附带风暴贯穿与连珠速射。',
  },
  crossbow: {
    subType: 'crossbow',
    name: '重弩 / 连弩 (Heavy Crossbow)',
    emoji: '🎯',
    speedRating: 'C',
    baseCooldown: 0.38,
    baseRange: 12.5,
    baseArc: 0,
    baseKnockback: 5.5,
    baseDmgMult: 1.4,
    baseCritChance: 0.18,
    recommendedClass: 'ranger',
    defaultVfxType: 'sniper_beam',
    defaultGlowColor: '#eab308',
    glowIntensity: 1.0,
    combatArchetype: 'pierce',
    perkName: '破甲重矢 (Armor Piercing)',
    perkDescription: '弩矢强力穿透 2 个敌方目标，击退沿途所有敌人',
    styleDescription: '高穿透机械重弩，蓄能激发，适合应对聚集的大群魔物。',
  },
  wand: {
    subType: 'wand',
    name: '魔杖 / 灵杖 (Arcane Wand)',
    emoji: '🔮',
    speedRating: 'A',
    baseCooldown: 0.2,
    baseRange: 11.0,
    baseArc: 0,
    baseKnockback: 2.2,
    baseDmgMult: 0.85,
    baseCritChance: 0.1,
    recommendedClass: 'mage',
    defaultVfxType: 'energy_orb',
    defaultGlowColor: '#8b5cf6',
    glowIntensity: 1.2,
    combatArchetype: 'homing_elemental',
    perkName: '灵能飞弹 (Magic Missile)',
    perkDescription: '引导式纯净法球，自动小幅修正弹道追踪最近的目标',
    styleDescription: '奥术师的标准施法工具，轻巧敏捷，释放自导奥术飞弹。',
  },
  staff: {
    subType: 'staff',
    name: '法杖 / 贤者权杖 (Archmage Staff)',
    emoji: '🪄',
    speedRating: 'C',
    baseCooldown: 0.45,
    baseRange: 13.0,
    baseArc: 0,
    baseKnockback: 4.0,
    baseDmgMult: 1.6,
    baseCritChance: 0.14,
    recommendedClass: 'mage',
    defaultVfxType: 'elemental_blast',
    defaultGlowColor: '#ec4899',
    glowIntensity: 1.4,
    combatArchetype: 'elemental_rapid',
    perkName: '元素爆轰 (Cataclysmic Burst)',
    perkDescription: '弹头在命中或终端产生元素范围爆炸，造成大范围溅射',
    styleDescription: '重型施法权杖，法术毁天灭地，法师装备可引发烈焰冰霜连锁爆破。',
  },
  hammer: {
    subType: 'hammer',
    name: '战锤 / 雷霆巨锤 (Warhammer)',
    emoji: '🔨',
    speedRating: 'C',
    baseCooldown: 0.48,
    baseRange: 2.2,
    baseArc: Math.PI * 0.9, // 162 deg
    baseKnockback: 8.5,
    baseDmgMult: 1.55,
    baseCritChance: 0.06,
    recommendedClass: 'warrior',
    defaultVfxType: 'ground_slam',
    defaultGlowColor: '#e0e7ff',
    glowIntensity: 1.3,
    combatArchetype: 'slam',
    perkName: '震荡波 (Shockwave Slam)',
    perkDescription: '重击地面迸发震波，眩晕击退近身全部敌军',
    styleDescription: '超重型钝击兵刃，毁伤与击退登峰造极，战士专精专属。',
  },
  shield: {
    subType: 'shield',
    name: '坚盾 (Tower Shield)',
    emoji: '🛡️',
    speedRating: 'C',
    baseCooldown: 0.6,
    baseRange: 1.8,
    baseArc: Math.PI * 0.6,
    baseKnockback: 6.0,
    baseDmgMult: 0.5,
    baseCritChance: 0.05,
    recommendedClass: 'warrior',
    defaultVfxType: 'slash_arc',
    defaultGlowColor: '#94a3b8',
    glowIntensity: 0.5,
    combatArchetype: 'slam',
    perkName: '盾牌冲撞 (Shield Bash)',
    perkDescription: '架盾抵挡正面巨额伤害，并以盾击震晕近身目标',
    styleDescription: '副手防御重器，架盾时大量吸收物理与投射物伤害。',
  },
  totem: {
    subType: 'totem',
    name: '圣图腾 (Sacred Totem)',
    emoji: '🗿',
    speedRating: 'B',
    baseCooldown: 1.0,
    baseRange: 0,
    baseArc: 0,
    baseKnockback: 0,
    baseDmgMult: 0,
    baseCritChance: 0,
    recommendedClass: 'mage',
    defaultVfxType: 'energy_orb',
    defaultGlowColor: '#eab308',
    glowIntensity: 1.5,
    combatArchetype: 'homing_elemental',
    perkName: '不死庇佑 (Totem of Undying)',
    perkDescription: '在受到致命伤时代替英雄碎裂，赋予短暂无敌与全量生命再生',
    styleDescription: '蕴含无上神力的神秘圣物，保护持用者免于死亡厄运。',
  },
};
